# Generated by Django 3.2.3 on 2021-05-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('strength', models.CharField(blank=True, max_length=20)),
                ('pack_size', models.CharField(blank=True, max_length=30)),
                ('price_BDT', models.FloatField()),
                ('medicine_pic', models.ImageField(default='default.png', upload_to='medicine_picture')),
            ],
        ),
    ]
