# Generated by Django 3.2.3 on 2021-05-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('contact_number', models.IntegerField()),
                ('specialist', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(default='default.png', upload_to='profile_pictures')),
            ],
        ),
    ]
